export const MESSAGE_CREATED = "MESSAGE_CREATED";
export const MESSAGE_DELETED = "MESSAGE_DELETED";
export const MESSAGE_UPDATED = "MESSAGE_UPDATED";
export const USER_CREATED = "USER_CREATED";
export const USER_ONLINE = "USER_ONLINE";
export const USER_TYPINGS = "USER_TYPINGS";
